/**
 * The assistant's tool catalog and skills library.
 *
 * Tools are defined once (JSON Schema) and exposed to both providers through
 * the stdio MCP proxy. Every tool except the `server: true` ones is executed
 * in the browser against the editor store, so the assistant edits the exact
 * same state the user sees. Every tool is defined in a `*.tools.ts` sibling
 * of the component that exposes the same feature to the user and aggregated
 * here, so the UI and the model always offer the same catalog.
 */

import { AI_PANEL_TOOLS } from "@/cut/components/AiPanel.tools";
import { TEXT_LAYOUT_IDS, TEXT_LAYOUT_NOTES } from "@/cut/lib/textCompose";
import { textLookCatalog } from "@/cut/lib/textLooks";
import {
  DEFAULT_WORDS_PER_CUE,
  MAX_WORDS_PER_CUE,
  MIN_WORDS_PER_CUE,
} from "@/cut/lib/cueChunk";
import { CAPTION_STYLES } from "@/cut/lib/subtitles";
import { wordEffectCatalog, WORD_EFFECT_IDS } from "@donkeycut/effects-kit";
import { textMoveCatalog } from "@/cut/lib/textMotion";
import { OVERLAY_ANIMATION_TOOLS } from "@/cut/components/AnimationTiles.tools";
import { AUDIO_TOOLS } from "@/cut/components/AudioPanel.tools";
import { EDITOR_TOOLS } from "@/cut/components/Editor.tools";
import { EFFECT_TREATMENTS, EFFECTS_TOOLS } from "@/cut/components/EffectsPanel.tools";
import { ELEMENTS_TOOLS } from "@/cut/components/ElementsPanel.tools";
import { VIDEO_GEN_TOOLS } from "@/cut/components/GeneratePanel.tools";
import { IMAGE_GEN_TOOLS } from "@/cut/components/ImageGenPanel.tools";
import { INSPECTOR_TOOLS } from "@/cut/components/Inspector.tools";
import { LIBRARY_TOOLS } from "@/cut/components/LibraryView.tools";
import { PREVIEW_TOOLS } from "@/cut/components/Preview.tools";
import { REMOVAL_TOOLS } from "@/cut/components/RemovalPanel.tools";
import { SCENE_TOOLS } from "@/cut/components/SceneCard.tools";
import { SIDE_PANEL_TOOLS } from "@/cut/components/SidePanel.tools";
import { STOCK_TOOLS } from "@/cut/components/StockPanels.tools";
import { SUBTITLES_TOOLS } from "@/cut/components/SubtitlesPanel.tools";
import { TIMELINE_TOOLS } from "@/cut/components/Timeline.tools";
import { TOP_BAR_TOOLS } from "@/cut/components/TopBar.tools";
import { TRANSITIONS_TOOLS } from "@/cut/components/TransitionsPanel.tools";
import {
  AUDIO_EFFECT_IDS,
  gradePresetCatalogText,
  HSL_BANDS,
  LOOK_EFFECTS,
  OVERLAY_ANIM_STYLE_IDS,
  OVERLAY_LOOP_STYLE_IDS,
} from "@donkeycut/effects-kit";
import type { AiToolDef } from "../../lib/aiToolDef";
import { GOOGLE_FONT_IDS } from "../../lib/fontCatalog";
import { FONTS, TRANSITION_STYLE_IDS } from "../../lib/types";

export const AI_TOOLS: AiToolDef[] = [
  ...AI_PANEL_TOOLS,
  ...PREVIEW_TOOLS,
  ...TIMELINE_TOOLS,
  ...INSPECTOR_TOOLS,
  ...REMOVAL_TOOLS,
  ...ELEMENTS_TOOLS,
  ...EFFECTS_TOOLS,
  ...OVERLAY_ANIMATION_TOOLS,
  ...TRANSITIONS_TOOLS,
  ...SUBTITLES_TOOLS,
  ...AUDIO_TOOLS,
  ...IMAGE_GEN_TOOLS,
  ...VIDEO_GEN_TOOLS,
  ...SCENE_TOOLS,
  ...STOCK_TOOLS,
  ...LIBRARY_TOOLS,
  ...SIDE_PANEL_TOOLS,
  ...TOP_BAR_TOOLS,
  ...EDITOR_TOOLS,
];

/** Deep documentation the model can pull in on demand. */
export const AI_SKILLS: Record<string, string> = {
  "editor-overview": `# Cut editor overview
Cut is a local, project-based short-video editor. Each project has an output aspect ratio "W:H" — presets 16:9, 9:16, 1:1, 4:3, 3:4, 2:1, or any custom ratio like 9:5 — rendered with the frame's short side at 1080px and switchable from the pill in the top bar; the current one is in editor_state project.aspect. Layout:
- Left icon rail tabs: Media (user-imported files + Exports list), Library (shared reusable assets), Video (stock clip browser — footage + talking characters — beside the AI video generator), Image (stock images beside the AI image generator), Audio (AI voiceover + audio files), Text (title presets), Subtitles (transcript editor), Publish (caption/tags/sound metadata). Camera/mic recording lives in the top bar next to the aspect picker.
- Media shows only what the user imported. Everything Cut makes carries an origin tag (generated, voiceover, recording, stock, freeze, chat — see \`media\` in editor_state) and lives where it was created — media you make previews on a card in this chat, panel renders sit in their job lists; a "…" menu on each files it into Media or the Library, and every card drags onto the timeline. Deleting a chat thread deletes the chat media the user never placed or filed away.
- Center: the video preview canvas (composited at the project's frame size) with draggable text overlays and subtitle captions.
- Right: the Inspector — its content follows the selection (video clip, overlay video, soundtrack clip, title, or cue).
- Bottom: the timeline (resizable by dragging its top border). Rows top-to-bottom: the video tracks in z-order (positive tracks, then track 0, then negative tracks behind it), soundtrack lanes (green), titles (purple), subtitle tracks (amber, when enabled). Every track is free-positioned in time.
Everything autosaves to the project folder. Undo/redo is unlimited (⌘Z / ⇧⌘Z).
Times are in seconds on the shared timeline. The playhead is currentTime; a skimmer previews under the mouse without moving the playhead.`,

  "timeline-editing": `# Timeline editing
- Every track is free-positioned: items carry a start time, gaps are allowed, and a track-0 gap plays black (and silence). videoTrack entries in editor_state report gapBefore where one exists.
- A delete removes the item asked for and nothing else: a title, sticker, caption or soundtrack clip laid over a deleted clip is still there afterwards, at its full length. While track 0 is the only video track, deleting a track-0 clip ripples: the span it occupied closes, later items on every track slide left together, and anything standing over the span falls back to where the span started. A gap that already existed stays. With overlay video tracks present the delete leaves its gap (remove_gap closes it by sliding that track's later clips left). Deletes on other tracks remove just that item.
- Two ways to move a track-0 clip: place_clip sets its start (respects gaps, slides right if the spot is taken); move_clip reorders by index, opening a slot at the landing point — clips after it shift right, every other gap survives. Index-based inserts (freeze_frame, generated clips) open a slot the same way.
- add_clip puts a project asset on the timeline the way a drag does: video/image onto track 0 (a \`start\`, an \`index\` insert, or appended at the end), audio onto the soundtrack.
- Overlay video: a video/image asset can sit on a track above track 0 (track 1, 2… — topmost wins). A full-frame overlay covers everything below it; give it a layout to share the frame — top/bottom/left/right halves for a split screen, pip for a floating corner box, or a custom region rect. add_overlay_video creates one from a media asset; update_overlay_video moves/trims/regions/mutes/hides it. The user makes them by dragging media above track 0; they drag the region in the preview.
- A clip's timeline length is (out-in)/speed; total duration runs to the last clip's end, gaps included. Transitions blend at cuts and never change layout or length.
- trim_clip changes in/out inside the source media. in >= 0, out <= source duration, out-in >= 0.1.
- Resizes ripple the same way deletes do: while track 0 is the only video track, a track-0 trim or speed change slides everything past the clip's tail — clips, titles, captions, soundtrack — with the moved edge, in both directions, every existing gap keeping its width. With overlay video tracks present, growth pushes the track-0 run and a shrink leaves a gap.
- set_speed sets a clip's playback rate; it changes the clip's timeline length and carries the timeline behind it like a trim.
- set_transition joins a clip into the next one (0–2s, ${TRANSITION_STYLE_IDS.length} styles); set_animation animates one clip's own entrance/exit — read the transitions-and-fades skill before styling cuts. Splitting or deleting clears the affected transition. A transition is a bar on its own row at an absolute time, so an edit can leave one lining up with nothing: every timeline mutation reports those as \`parkedTransitions\`, and clearing them (remove_transition) is part of finishing the edit. Grading a clip's picture is the color tools (set_color_preset, set_color_grade, set_color_curves, set_color_wheels, set_color_hsl — read the color-grading skill); a stylized post treatment (grain, VHS, halation…) is add_effect, dropped over the stretch of timeline it covers — as is a treatment on the sound (echo, reverb, telephone…).
- Cutting a clip's background away — the AI person matte, ink around the silhouette, a fill behind the subject — is the cutout suite (set_removal, set_removal_stroke, set_removal_background); read the background-removal skill.
- split_at cuts the track-0 clip under that time into two clips at the exact frame. With a soundtrack or overlay clip selected it splits that instead.
- The Media and Library panels take the same gestures: ⌘/⇧-click a tile, or sweep a rubber-band over the grid, and dragging any picked tile onto the timeline lays the whole set down one after another from the drop point.
- The user can multi-select (⌘/⇧-click, or sweep a rubber-band over empty track space) across every kind at once — clips, audio, titles, cues. Deleting or copying acts on the whole selection, and dragging any member moves the set as one: every item shifts by the same time, relative spacing kept, while unselected items slide out of the way and flow back. A selection of one kind on the multi-row tracks (audio, titles) also retracks together on a vertical drag, one row past the end opening a new track. A hover chip on each video clip toggles its own audio.
- Anything can be hidden instead of deleted: it stays on the timeline (grayed) but drops out of playback and export — a hidden video clip plays black and silent. Per item: set_clip_hidden, or the \`hidden\` field on update_overlay_video/update_overlay/update_audio. A transition bar hides the same way (set_transition_hidden): it keeps the cut it sits on so nothing else claims that boundary, and the cut renders hard. Whole rows: set_track_hidden (video/soundtrack/text/subtitles/transitions) and set_track_muted (video) — the eye/speaker toggles on the track headers.
- detach_audio lifts a video clip's sound to the soundtrack track (and mutes the clip) so audio can be cut independently of video.
- freeze_frame grabs one frame (default: the playhead — what the user currently sees) as a still clip and inserts it, by default at index 0 as a cover/hook frame ("make this the first frame"). The still is baked at the project's current aspect with the clip's framing applied; if the user later switches aspect they should capture a fresh one. \`with_elements\` bakes the composited picture instead — titles, captions and effects burned in — which is what a cover frame carrying the video's own text needs. The user reaches the same still by right-clicking the preview canvas: Copy frame puts that picture on their clipboard, and ⌘V drops it on the timeline.
- set_framing: per-clip Fit (letterbox) vs Fill (crop to cover the box), plus zoom 1..4 to push further in. Whenever the picture overflows, panX/panY position the crop window; in the preview a grey outline shows the part being cropped away, and the user drags that outline to slide the crop (dragging the clip itself moves its box). The controls live in the Inspector under "Framing" when a video clip is selected. Landscape footage usually wants fill + a pan that keeps the subject.
- update_clip also carries a clip's resting transform: rotation and opacity, alongside its region (layout/region) and zoom. Use these for a tilted or faded layer; set_clip_keyframes is for a transform that moves over time.
- set_clip_style rounds a clip's corners, strokes a border ring, and casts a drop shadow from the clip's shape — mask included, so a circle-masked webcam gets a circular shadow. The floating-cam look is one recipe: put the clip on an upper track, region it small (update_clip region or the preview handles), mask it with kind circle, and give it a soft shadow.
- The user can copy/paste any selected segment (video, overlay video, audio, title) with ⌘C/⌘V; pastes aim for the playhead and slide right to free space.
- Zoom: set_view pxPerSec (12..800) or fit. The timeline panel height: set_view timelineH (170..600).`,

  "color-grading": `# Color grading
Grade like a colorist: read the image, correct it, then style it — in that order.

**Read before you write.** Call read_color_stats on the clip before grading (never grade blind) and again after a move to verify it landed. The quantiles tell you where the tones sit: p2 well above 0 = lifted/milky blacks, p98 well below 255 = no real whites (flat), a p50 far from ~118 = exposure off. warmth > 1 reads warm, < 1 cool; meanSat under ~0.15 reads muted, over ~0.35 vivid. The clip's current color state is in editor_state (colorPreset, grade, curves/wheels/hslBands).

**Correct first.** Balance and tone before any look: auto (set_color_grade auto:true) is a computed starting point — exposure to middle gray, contrast stretch, gray-world white balance — then nudge. Neutralize a cast with temperature/tint before styling warmth on top, or the style fights the cast. Every value 0 is neutral and fields patch, so small moves are cheap; slider range is ±50.

**One model, layered.** A clip's color is one grade: an optional preset underneath, manual adjustments on top. set_color_preset never touches the manual layer and vice versa; intensity (amount) scales only the preset. Preview, thumbnails, and export render the same numbers.

**Which tool for which job.**
- set_color_preset — a fast, coherent base. Catalog: ${gradePresetCatalogText()}. Start amount around 0.6–0.8 and tune to taste; protect_skin when a strong palette would discolor faces.
- set_color_grade — the basic sliders: exposure/contrast for tone, highlights/shadows for the ends, temperature/tint for balance, saturation/vibrance for color amount (vibrance favors the muted colors and spares what is already rich).
- set_color_curves — tonal shape: curve_contrast for an s-curve, fade for lifted film blacks, explicit points when you need a precise remap; red/green/blue channels split-tone tonally (a touch of blue lifted in shadows = cool shadows).
- set_color_wheels — split-toning by range: push shadows toward one hue and highlights toward another (teal shadows dx<0, warm highlights dx>0 is the classic pairing); luma trims each range's brightness.
- set_color_hsl — one hue only (${HSL_BANDS.map((b) => b.id).join(", ")}): "sky bluer" = aqua/blue sat up, "mute the greens" = green sat down, skin smoothing = orange band, gently.
- match_color_grade — a reference exists (attached image or another clip): the grade is computed from the pixels (quantile-matched curves + saturation), then refine with the tools above. Matching adjacent clips for consistency is this too — match the odd clip to its neighbor.

**Craft.** Skin lives around orange at modest saturation — check faces after strong saturation, hue, or wheel moves, and reach for protect_skin or a gentle orange-band correction rather than abandoning the look. Keep adjacent clips consistent: one preset + per-clip correction reads as one film; different presets per clip read as a slideshow. Strong looks sit better with contrast established first. Grades are per-clip — "grade the whole video" means every clip, same recipe.`,

  "background-removal": `# Background removal (Cutout)
Every video clip — any track, stills too — can carry a cutout, the Inspector's Cutout tab: the clip's picture keys to an alpha matte, the subject stays, and where the background was, lower tracks or the project background show through. Preview, timeline thumbnails, and export render the same matte. A long clip tracks in parts automatically — cutout length needs no special handling.
- set_removal runs both directions: \`remove\` "background" keeps the selection and drops everything around it; \`remove\` "subject" drops the selection and keeps the rest. The selection is the same either way, so flipping the direction on an existing cutout is instant — no new bake, no new charge.
- set_removal mode "auto": the AI person matte. The free on-device pass starts from one tool call here (in the panel it waits for the user's Apply press) and lands in seconds. The hosted quality pass (spends credits like generation) upgrades hair and edge detail only on an explicit ask: the panel's Apply button, or the tool's \`refine\` flag when the user asks for the upgrade. Custom mode still starts from the user's Apply press (or this tool with \`subject\`) — hand-instructions include that step. Each cutout clip reports under \`removal\` in editor_state videoTrack/overlayVideo — mode, the \`removes\` direction, matte readiness ("ready (quick)" / "ready (quality)" / "none"), and a running matte's progress — and wait_for_renders settles on that work, so claims about a finished cutout come from there. Short of credits, the quick matte stands and the panel offers the upgrade.
- set_removal mode "custom" with \`subject\`: an arbitrary object by description — "the dog", "the red car" — matted and tracked through the clip (spends credits, less than a brushed track). Every match of the words is kept, so "cut out the dog" is one call. Picking one exact instance among lookalikes is hands-on: the user picks Custom in the Cutout tab, paints it on the preview with the Brush and Erase tools (strokes paint exact pixels), and presses Apply — the hosted tracker follows those exact strokes; with a subject set too, the strokes refine which instance the words picked.
- set_removal_stroke draws ink around the kept silhouette — glow, hand-drawn, straight cut, solid, offset (a thrown silhouette copy placed with offset_x/offset_y), dotted — with color, width, and feather (edge softness). The die-cut sticker look is a white solid or cut stroke.
- set_removal_background fills in behind the subject inside the clip's own picture: a flat color or a project image. For new scenery behind a person, an image fill here or scenery on a lower track both read; the lower track keeps the scenery independently editable.
Panel geography, for hand-instructions: the Cutout tab is one flat pane. One segmented Remove control at the top holds every choice — Off / Background (keep the person, mode "auto") / Subject (drop the person, mode "auto" with remove "subject") / Custom (the brush flow, mode "custom") — picking Background or Subject starts the free matte at once, Off keeps the cutout stored while showing the plain picture, and while a bake runs the other segments wait — Cancel first to change course. With a cutout on, the Stroke and Fill sections stack underneath, each behind its own on/off switch (Fill offers Color / Image; the Image list shows pictures imported into Media).
Recipes: "remove the background" on a person = auto — green-screen and plain-backdrop shots included, the matte keys them. "Cut out the dog" = custom with subject "the dog". "Put me on a beach" = auto + the beach behind (background image or lower track). Sticker/die-cut = auto + white cut stroke. A bold silhouette pop = offset stroke in a loud color. Turning it off = set_removal mode "off" — the picture shows plain, and the whole cutout (matte, stroke, fill) stays stored, so any on-mode brings it straight back.`,

  "watching-and-cutting": `# Watching footage & cutting by content
When a request depends on what the footage actually contains — "cut the dead air", "clip the best moment", "remove the boring part", "split where the scene changes" — watch it first. Never guess at content you haven't seen.

Your eyes and ears:
- watch_video(clip_id | asset_id, from?, to?, interval_seconds?): samples the SOURCE on a dense steady floor, keeps only the frames that actually differ, and returns them as timestamped contact sheets — cells read left→right, top→bottom, each burned stamp is source seconds, and a gap between stamps means nothing changed there — plus sceneChanges, hard-cut times refined to about a third of a second of the true boundary, and — when the clip has captions or the source's transcript exists — a fused timeline placing each frame inside the speech it belongs to. Coverage ends where the result says: when truncated (span bound, frame cap, or time budget), continue from coveredTo. A shot shorter than the sampling step can fall between candidates — where short cuts matter, re-watch narrow with interval_seconds 0.5–1. Watching builds the source's frame map, persisted on the asset; each media entry's "mapped" spans list where that map exists, and the first watch or listen of a source starts a background sweep that maps the rest, transcript included ("watching": true marks it running; the spans grow as segments land). Use the map to aim your watches — a mapped span is NOT footage you have seen; only the sheets returned to you in this conversation are, so watch any span before you cut inside it.
- note_source(clip_id | asset_id, notes: [{from, to, text}]): writes what you saw onto the source, in source seconds. The sheets are conversation-local and the oldest media drops out as the chat grows; a note is permanent — it saves with the project, comes back as \`observed\` on the media entry in every later turn and chat, and is returned to you by get_state and by watch_video's \`recorded\`. This is how a source longer than one look becomes usable.

**Seeing all of it.** Every result carries \`coveredTo\` and \`unwatchedSeconds\`. A \`to\` you passed yourself ends the call with \`truncated: false\` and the rest of the source unseen — that is not coverage. Any ask about the video AS A WHOLE — "what happens in this", "summarize it", "replicate/recreate this", "match this style", "how does it end" — means watching from 0 until \`unwatchedSeconds\` reaches 0, however many calls that takes. Watching a slice and describing the whole is how you end up reporting text that isn't there and putting the opening line at the end. Aiming a watch at one span is for a question about that span. One call reaches as far as its ceilings allow: a 600s span, 150 decodes, 36 kept frames, 90s of decoding — so at \`interval_seconds\` 0.5 a call covers at most 75s of source, and far less where the picture keeps changing. A source of a minute or two is a few calls; a source of an hour is not something to grind through frame-dense from 0. There, sweep it coarse first (\`interval_seconds\` 15–30 end to end) to learn its shape, then watch the spans that matter at a dense floor.

**Watch, write, decide.** Watching builds a record and the record is what you work from. Every pass ends with note_source: the span you just looked at and what it showed — on-screen text word for word, what happens, how it is shot, where the cuts land. Do it while the sheets are still on screen; the conversation drops its oldest media as it grows, and a watch nobody wrote down is a watch spent for nothing. Watching a source that still has an unrecorded look behind it is refused, so the loop is one pass, one note, next pass. The record comes back to you as \`observed\` on the media entry, in full from get_state, and as \`recorded\` and \`unnoted\` on every watch result. An hour of footage is decided from notes you can hold: sweep it coarse (\`interval_seconds\` 15–30) and note its shape, then watch the spans that matter at a dense floor and note those closely — a close note replaces the coarse one over the same span. Before you plan an edit, read \`observed\` and \`unnoted\`: a span already described needs no second look, and one still blank does.

**Reading on-screen text.** Recreating a video's titles, captions or kinetic typography is a transcription job, so read every card in order with its own timing: watch the whole source at \`interval_seconds\` 0.5 (a line that builds a word at a time — "You" → "You know that building" → "is everything today" — is one card, and a 1s floor collapses or skips those steps), and write each card's text, its in/out, its color and its position into note_source as you read it — that record is what you build the cut from a turn later, when the sheets are gone. Copy the text exactly, including the lines you would have trimmed; a fragment placed as if it were a whole card ("I got half of" without "my clients from Linkedin last year") is a misquote of the user's reference. Cards frequently continue across cuts — before you decide a card is finished, check the next one for the rest of its sentence.
- detect_silence(clip_id | asset_id, threshold_db?, min_silence?): silent stretches in source seconds; with clip_id each also carries its timeline times.
- detect_beats(clip_id | asset_id, regenerate?): the music's beat grid — bpm and beat times in source seconds, plus timelineBeats ready for split_at with clip_id. The grid persists on the asset, draws as yellow dots on its clips, and every drag or trim snaps to it. "Cut to the beat" / "sync to the music" means detect, then split or place at the timeline beat times; the stored grid carries the user's hand edits, so re-detect only when they ask.
- capture_frame(t?): one composited frame, at the given time in seconds or the playhead — for checking the final look. Surveying footage is watch_video's job.

The flow for "edit this for me":
1. get_state — every clip, its trim (in/out), speed, gaps, and the other tracks.
2. Speech? subtitles_generate first — cue timings are timeline seconds and say what is said when.
3. watch_video each distinct source (or the ranges in question); note scene changes and what happens where.
4. Plan in thoughts: group the cues into sentences and thoughts, decide which thoughts stay whole, then detect_silence to find where the speaker actually pauses. Cue timings approximate the audio — a trailing word often spills past its cue — so aim every speech cut into a detected silence span, and aim loose: up to a second of spare air on each side beats a tight cut, because the refine step trues the edges after. A cue boundary with no silence span around it means the speech runs continuously there, so leave that joint alone.
5. Execute: split_at (timeline s) to divide, delete_item to drop a segment, trim_clip (source s) to tighten edges, place_clip/move_clip to close gaps or reorder, set_speed to compress slow stretches. Batch each wave in one round: splits don't move times, so issue every planned split_at together, then every delete together. Every timeline mutation returns the updated track-0 and soundtrack rows (ids, starts, lengths) — read the new ids from the result and keep cutting; get_state between steps is a wasted round.
6. Refine: refine_speech_cuts with every recut clip id, and with the \`pace\` the request asked for. It measures the recording's own room tone and voice level, finds where each word truly starts and finishes, and re-trims every edge to sit a beat clear of one, keeping the clips' spacing. It reads sound, not intent — leave out a clip whose edge you placed mid-speech on purpose.
7. Verify by ear: listen_audio at each edge the refine flagged, plus a spot-check or two (scope from/to to ~2s around the joint), and check the first and last words arrive whole and the hand-off into the next thought sounds natural. A clipped word → widen that trim deeper into the silence and listen again. After a heavy edit, listen once end-to-end. seek + capture_frame when the change is visual.

Time math (get this right):
- watch_video, detect_silence, and trim_clip speak SOURCE seconds; split_at and place_clip speak TIMELINE seconds.
- timeline_t = clip.start + (source_t − clip.in) / clip.speed, valid while source_t is inside [in, out]. Each watch result's clip block carries this formula with the real numbers filled in.
- The same source can appear in several clips — map per clip.

Cutting speech well: pace is part of the message, and it is set in one place — refine_speech_cuts' \`pace\`. "Fast paced", "punchy", "tight" means pace: fast there; a calm piece means relaxed. Placing your own edges closer to the words is not a faster cut, it is a clipped one: a word's tail runs past its cue, the ear hears the truncation, and no amount of tightening reads as energy. So cut loose — up to a second of spare air on each side — and let the refine step take it back to the beat the pace asks for. Shorten a long pause to that beat rather than deleting it; speech butted directly together reads as rushed however fast the piece is meant to be. Prefer split_at + delete_item, then place_clip to close the gap (a beat of black may be wanted — ask the cut, not the tool); trim_clip only tightens a clip's edges.`,

  "transitions-and-fades": `# Transitions, animations, looks & fades
Route the ask to the right feature:
- set_transition: a styled join between one video clip and the next, blended across the cut. It never moves clips or shortens anything, and it plays only while the pair touches. One style, audiocross — the cross dissolve — blends the sound alone: the picture cuts while the two clips ramp equal-power past each other, half the length either side of the cut, each playing into the other's time out of the media its trim left behind, so the mix holds its loudness through the join (it plays at cuts only, so it does nothing on a clip's open head or tail; a clip trimmed to the end of its source has nothing to cross with and its side stops at the cut). In the UI it is picked from the Effects tab's Sound family, beside the treatments on the sound, and its bar sits across the cut rather than before it; every style that blends the picture is picked from the Transitions tab.
- set_animation: one clip's own entrance ("in") or exit ("out") — the clip fades/zooms/pops/slides on its own edge. Never moves neighbors. For "fade this clip in", "make it slide in", use this. A wipe is a transition, not an animation.
- set_project_fade: the whole video fades in from black at the start and/or out to black at the end — picture and full mix (titles, captions, soundtrack). Survives clip reordering. For "fade in the video", "fade to black at the end", use this.
- set_background: the color of the frame itself, behind everything, for the whole cut. For "make the background white", or any cut whose picture is titles and shapes rather than footage. Covered in the graphics skill.
- update_audio fadeIn/fadeOut: audio-only ramps on one soundtrack clip ("fade the music out").
- An ask beyond every preset here — a reference template, a grid or mosaic reveal, a multi-panel build — is a construction job: the graphics skill's composite-builds section shows how overlay video tracks, masks, and keyframes compose into it.

set_transition styles (clipId = the leading clip; 0 clears, max 2s): crossfade blends; crosszoom adds a zoom punch; dipblack/dipwhite dip through a solid color; blur defocuses through the cut; pushleft/right/up/down shove the old frame out; wipeleft/right/up/down reveal with a hard traveling edge; circleopen/close and splitopen/close are shape reveals; audiocross — the cross dissolve — cuts the picture and dissolves only the sound across the cut, for a handover the eye takes as a cut and the ear takes as a blend. Directional names describe the motion.
set_animation styles: fade (audio follows), zoom, pop, slideleft/right/up/down — the slide names are the motion direction (slideleft enters from the right edge moving left, or exits off the left). Each edge holds one effect and the last pick wins: set_animation on a transitioned edge replaces that transition, set_transition clears the animations adjacent to its joint.

Bars and the debris they leave: a transition lives on the transitions row as its own object at an absolute time, listed in editor_state \`transitions\` with the boundary it \`plays\`. It plays whatever cut or clip edge its window lines up with; a bar lining up with nothing reads \`parked: true\` and plays nothing — the badge is on the row, the blend is gone. Moving, retiming, or replacing clips is what parks a bar, so every timeline mutation returns \`parkedTransitions\` when its edit left one. Own that debris in the same turn you make it: a bar you parked and know the intent of, reattach with set_transition/set_animation on the edge it belongs to, or clear with remove_transition. When you can't tell what a parked bar was for — it predates your edits, or the user's ask doesn't say where the blend should end up — do not guess and do not leave it silent: name what's there ("there's a 0.5s dip to black at 29.4s that isn't on a cut any more") and ask whether to remove it or move it to a specific joint. The same holds for anything else on the timeline that reads as leftover from your own edits: say what you see and confirm before deleting the user's work.
Picking for a vibe: "smooth" → crossfade; "let the sound carry over a hard cut", "audio crossfade", "cross dissolve", "dissolve just the audio" → audiocross; "punchy/energetic" → crosszoom or a push; "dramatic scene change" → dipblack 0.5–0.8s; "dreamy" → blur (or the dreamy look); "retro" → vhs or vintage look. Between clips 0.4–0.8s reads well on the picture; 1s+ is slow and cuts total duration. The cross dissolve is shorter — 0.3s covers the jump in room tone without letting two voices be heard at once, and it asks less of the trim each clip has left. The editing-taste skill covers when a joint should stay a hard cut and how to keep transition styling consistent across the video.
UI: select a clip → Inspector "Effects" opens the panel (Transition / In / Out / Looks tabs). Preview and export render the same treatment.
What the user sees on the transitions row: one badge per bar, and nothing else — the row holds no buttons, no placeholders, and no add-affordances. A playing bar is blue; a parked one is the same badge in grey. So a user reporting "greyed out transitions", "grey circles", or "dead/lingering transitions" on that row is describing parked bars, which are real objects saved in their project — never dismiss them as editor chrome or claim they won't export, because the badge is the transition itself. Read \`transitions\` in editor_state and answer from the parked entries there. A bar can also be hidden (set_transition_hidden): it grays out but keeps its cut, so the joint plays as a hard cut and the bar is there to switch back on — that is how to audition a cut without its blend. Grey elsewhere means something different: a clip, element, or track shown grayed is hidden (the \`hidden\` flag), which does drop out of playback and export.`,

  "graphics": `# Graphics: titles, shapes & stickers
The title lanes hold three overlay element kinds, all sharing timing (start/end), center position (x/y fractions 0..1), rotation (degrees), opacity, and a lane; \`overlays\` in editor_state lists them with their \`kind\`. All burn into the export exactly as previewed.
Rows are how elements stack (\`lane\`, 0 = the front row; a higher row draws further back). Two elements on ONE row never overlap in time — placing a title where a shape already sits slides it clear instead of laying it on top — so anything meant to sit over something else names a LOWER row: title on lane 0, the background shape behind it on lane 1. Every add tool and update_overlay take \`lane\`.
The frame's own color is set_background, not a full-frame rectangle: it fills the frame behind every clip and element, holds for the whole cut, letterboxes fitted footage, and shows through gaps on track 0. "Make the background white", a colored card behind a title sequence, a text-and-graphics video with no footage at all — all of them start with set_background. A rectangle element is for a panel or a band inside the frame, not for the frame itself.
A whole run of text — lines timed to speech, a lyric video, a kinetic-typography passage, a quote sequence — is add_text_sequence, one call. Design is opt-in: called with no look it lays a plain run — one readable face, one place in the frame, a short fade, no cards, no moves, the frame color untouched — which is what a bare "add the text" asks for. Name a look when the user asked for a designed run, and then the look is the design of the whole run, not one line: the frame color, the cards, and the ensemble the run walks across its length — faces, entrances, where successive lines land, and what each holds. Read the text-videos skill for the looks and the flow, and text-creativity for the fifty devices that keep a long run from reading flat. A designed run is composed in the call, never laid identical and then repaired element by element. A video needs no footage. Titles, shapes and stickers over a background color are a complete cut on their own: it plays, exports, and shares like any other. Build one by setting the background, then placing elements on the rows the stack needs — reach for footage only when the user asks for it.
Titles (add_title / update_overlay): text, size (frame px; the design short side is 1080), font (${FONTS.map((f) => `${f.id}=${f.label}`).join(", ")}), weight (400/700), color, shadow, plate (translucent dark backdrop). Type never leaves the picture: a line too wide for the room its anchor leaves is broken onto more lines as it draws, in the preview and in the export alike, so write the words at the size the design wants and leave the fitting to the renderer.
Shapes (add_shape): rect, ellipse, line, arrow. w/h are frame fractions; rect/ellipse take fill + fill_opacity, corner radius (rect), and an outline (stroke_color/stroke_width); line/arrow draw in \`fill\` with h as their thickness, and rotation gives them their direction (0° points right, 90° points down).
Stickers (add_sticker): a project image asset (generated cutouts in the Elements panel carry origin "sticker"); w is a frame-width fraction and height follows the source's aspect. Lottie JSON uploads become animated stickers that loop for the element's duration.
Custom stickers (create_sticker): one call generates the image, removes the background, adds the die-cut outline, and places it — use it when the user asks for a sticker of something they don't have (it spends credits like image generation).
Effects (add_effect): time-ranged treatments over the finished cut. Three families, one list: the picture treatments (${EFFECT_TREATMENTS.join(", ")}), the graded looks (${LOOK_EFFECTS.join(", ")}), and the audio treatments (${AUDIO_EFFECT_IDS.join(", ")}). A picture effect treats the footage and everything laid over it; an audio effect treats everything audible under its window at once — clip sound, upper-track sound and the soundtrack — so "make this bit sound like a phone call", "put an echo on that line", or "muffle the music here" is an effect element over that stretch, and a per-clip volume, fade or duck is the audio tools instead. A handover on the sound at a cut belongs to the transition on that cut — the audiocross style — not here. Placed like any element and tuned with \`amount\` (update_overlay), and trims like anything else: a picture effect dropped over a clip opens covering that clip, while an audio effect opens at the standard length wherever it was placed — a treatment on the sound is aimed at a moment, so give it the window you mean. One effect at a time reads best, amounts under ~0.5. Effects are stylized post treatments on a stretch of timeline; pure color — exposure, warmth, a cinematic or film palette on one clip — is the per-clip grading tools instead (color-grading skill), whose preset catalog is separate from the look effects.
Advanced text (update_overlay): italic, align (multi-line), letter_spacing (em), line_height, stretch_x/stretch_y (glyph stretch multipliers, the side grips' axis-only resize), stroke_color/stroke_width (em outline behind the fill), and richer shadows. Bundled Google families join the system set — ${GOOGLE_FONT_IDS.join(", ")} — and so do the user's own: a .ttf/.otf/.woff/.woff2 file dropped on the Library is offered in every project under a font id like "font:<id>". Editor_state lists the ones this account has under \`fonts\` — use an id from there instead of guessing at a family name, and when someone asks for a typeface that is not in the list, tell them the Library takes font files.
Animation (set_overlay_animation): every element takes preset In/Out ramps (${OVERLAY_ANIM_STYLE_IDS.join(", ")} — typewriter for titles only; the per-letter styles sweep a title character by character), a Loop (${OVERLAY_LOOP_STYLE_IDS.join(", ")}) that runs its whole duration, and a Move that says what it does WHILE it holds. A title takes one more: Words (${WORD_EFFECT_IDS.join(", ")}), which plays the line word by word — an emphasis travelling along a line that is fully up, or a build assembling the line as it is spoken. Entrances 0.3–0.6s read well; one loop per scene, sparingly; a move on the lines that matter. All of them are slots on the element, applied internally; the keyframe track (set_overlay_keyframes) is the separate power tier for motion the names do not cover, and slots compose over it.
Keyframes (set_overlay_keyframes): for motion no preset covers — a path across the frame, a slow push in, a drift that holds first. A key is a whole pose (position, scale, rotation, opacity) at a time in seconds from the element's start; the pose moves linearly between keys and holds outside them, and presets still compose on top. Two or three keys carry almost everything; reach for a preset first and keyframes when the user describes a specific path or timing. In the UI the diamond in the inspector adds a key at the playhead, and dragging the element then records into it. set_clip_keyframes is the same track on a video clip (any track): pans, push-ins, picture-in-picture flights, spins, and fades on the footage itself.
Masks (set_mask): trim any element or video clip to a shape — rect, square, circle, linear, mirror — with feather, invert, and its own keyframe track for reveals and wipes. The subject kind trims by the person in the shot (on-device segmentation; preview and export match): inverted sits the item behind the speaker, plain keeps it only on the speaker. Behind-speaker reads well when the speaker is clearly separated from the background; with no detectable person it degrades to the plain picture. Groups: the user can group elements (select several, Group in the inspector) — selecting one selects all, and moves/resize/rotate/timing ride together.
Composite builds: these primitives compose. Stacked overlay video copies, masks and their keys, pose keyframes, staggered starts, and shapes construct effects beyond any preset list. Given a reference (a screenshot or clip of an effect the user wants), reverse-engineer it:
1. Read the reference as layers. For each visible piece, decide what it is: live footage, a cropped or repeated slice of the footage, a solid graphic, text, or empty background.
2. Map each layer to a primitive. A slice of the picture = a copy of the same asset on its own overlay track (add_overlay_video, layout full, matching trim so every copy's picture lines up with the base) trimmed by a mask whose x/y offsets place it — a full-frame copy under a mask shows the true part of the picture at that spot, so masked copies tile back into the whole image. Gap lines and borders come from sizing masks under their spacing (track 0 left empty plays black through the gaps) or from stroked shapes. Solid panels are shapes; words are titles.
3. Map the timing. Pieces arriving one after another = staggered start times. Geometry that moves or grows = mask keys; opacity keys fade a piece in place. Pose keyframes and entrance presets (zoom, slide) move the picture UNDER the mask, sliding the slice out of register — save them for pieces where that motion is the point, and reveal aligned tiles with starts, mask keys, and opacity alone.
4. Work out the geometry as numbers before calling any tool. Any screen region converts to mask parameters by plain arithmetic: w and h are fractions of frame width and height — rect takes both, so it expresses any region on any aspect; a square's side rides frame width alone, and a shape meant to hold exact pixel proportions folds in project.frame's pixels — and x/y are the region's center measured from the item's own center. Write every piece's region and timing as numbers, check that together they lay out what the reference shows (coverage, spacing, alignment), then place them.
5. Build one representative piece and capture_frame it against the reference. Then build the rest and capture_frame again, mid-reveal and at the end: every cell present, slices aligned into the whole picture, the target region covered edge to edge. Fix what's off at the right level: a wrong number re-sets in place (set_mask and the keyframe tools overwrite), a mistimed copy retimes, and a wrong cell plan means deleting the copies you added (delete_item) and laying them again from the corrected list — the pieces you placed are yours to tear down. The build is done when the captured frame matches the reference.
All of it is regular timeline editing: free, live, and undoable.
Good TikTok titles: short punchy lines, high contrast (white/yellow + shadow or plate), size 72–110, keep inside the middle 80% of the frame (x 0.1..0.9, y 0.1..0.9), avoid the caption band (y≈0.8) when subtitles are on.
Tasteful graphics: shapes read best as accents (a highlight box behind a stat, an arrow pointing at the subject, a color bar under a title) — semi-transparent fills (fill_opacity 0.2–0.5) sit better over footage than solid blocks. One or two stickers a scene; size 0.15–0.3 of the frame width.
In the UI: the timeline toolbar adds Text; the Elements side-panel tab browses stickers and shapes and creates sticker images, and the Effects tab holds the effects — a click in any panel picks a tile, and dragging one onto the timeline is what places it; dragging in the preview places an element, its corner handle resizes, the top handle rotates; the Inspector edits every field.`,

  "text-videos": `# Text-driven videos: lyrics, kinetic type, quote cards
A video whose picture is words. Three pieces: the frame behind them (set_background, or the user's footage), the words themselves, and the clock that says when each line lands. For the device list — fifty ways to make a run of text worth watching — read the text-creativity skill.

**Design is something the user asks for.** "Add the text", "put what he says on screen", "add text from the audio" is a plain job: get the words and their times — the cues already in editor_state, a source's transcript, listen_audio, or subtitles_generate when the user wants a caption track — then place them with add_text_sequence and no \`look\`. That lays one readable face at one spot with a short fade, no cards, no moves, no tilts, and no repaint of the frame. Then align_to_audio: the times you placed came from a transcript, and that pass measures them against the mix's own waveform and moves each edge onto the speech. Reach for a look, cards, moves, or a variation only when the ask carries a design in it: a lyric video, kinetic type, a named style or vibe, "make it fun", a reference to match. A cut that comes back restyled when the user asked for words on screen is the failure this default exists to prevent.

**Two ways to carry the words.** A caption track is one styled row of text that follows a voice — it holds word timings, and one call restyles every line. Elements are separate titles and cards on the timeline — per-line face, per-line placement, per-glyph motion, a color card behind each line — which is what kinetic typography and lyric cards are made of. Captions for a song you want to sing along to; elements when each line is its own picture. Both burn into the export, and both play their words as they are said: word_highlight on the caption track, the words slot of set_overlay_animation on a title. Two families to pick from — an emphasis travels along a line that is fully up (the word lights, swells, or takes a card), and a build assembles the line as it is spoken (words appearing one by one, or a faint line going solid word by word).

**The looks.** A look is opt-in, and it is not one line's styling — it is the design of a whole run. It sets the frame color, the cards it cycles, the type, the entrance, the caption equivalent, AND the ensemble the run walks across its length: the faces it rotates through, the entrances, where successive lines land, and what each line does while it holds. So one add_text_sequence call already produces a composed, varied run:
${textLookCatalog()}

**Composing a run (this is the part that decides whether it reads as creative).** add_text_sequence takes the whole run in one call and walks the look's rotas by index, so no two neighbouring lines land the same. Steer it:
- \`variation\`: bold (default) walks faces, tilts, palette and moves; subtle keeps one face and varies placement and entrance; none lays every line identical — only for a run you are about to hand-compose yourself.
- \`layout\` overrides where lines land: ${TEXT_LAYOUT_IDS.map((id) => `${id} — ${TEXT_LAYOUT_NOTES[id]}`).join(" ")}
- \`emphasis\` per line: hero is markedly bigger and takes the look's hero move, whisper is small and quiet. Mark the hook, the title line, the punchline. Two or three heroes in a verse; a run where everything is a hero is a run where nothing is.
- \`section\` per line ("verse", "chorus", "bridge"): a new label restarts the type and color rotas, so a chorus does not look like the verse before it. Label every line of a song — it is the cheapest way to make three passages read as three passages.
- \`move\` per line: what it does WHILE it holds, separate from the entrance. The rota gives each line one already; name one when a specific line wants a specific move.
- Anything you set per line — font, x, y, rotation, in_style, color, size — wins over the ensemble.
Never lay a run at variation "none" and then repair it with a hundred update_overlay calls. Compose it in the call.

**A lyric video, from an audio track and the words.** The user has the song and the lyrics.
1. The song is in the cut (a soundtrack clip). \`get_state\` confirms it and gives the duration.
2. sync_lyrics with the lyrics text, one line per screen. It transcribes the cut, aligns the user's words to what it recognized, and writes the user's text — verbatim — onto a caption track with per-word times. Singing defeats recognizers; that is why the wording comes from the user and only the clock comes from the transcript.
3. Dress it: set_caption_look with a look id (karaoke-glow for words lighting up, neon-club, serif-mood…), or accent_mode on its own to pick what each sung word does — pop swells it, box puts a card behind it, build has the line appear a word at a time, fill leaves it faintly up and solidifies each word as it lands — or add_text_sequence from_captions to turn the same timed lines into full-frame cards. Going the element route, re-send the lines yourself with emphasis and section on them rather than from_captions — from_captions carries the timing but knows nothing about which line is the hook.
4. Check it: sync_lyrics already snaps its lines to the mix, and align_to_audio re-runs that pass any time (on the caption track, or on the elements of a run with target elements). Then seek + capture_frame at three or four lines that landed on DIFFERENT rota steps, and listen_audio across one of them. A single line still sitting early or late retimes with update_cue.
With no lyrics text, transcribe with subtitles_generate and work from the cues it wrote.

**Words over the user's footage.** Same flow, with the over-footage look (or any look with no cards) and \`background: false\` — the clips keep playing and the words ride above them. Aim them off the caption band when captions are also on, and prefer layouts that stay out of the middle of the shot.

**Words on plain color.** A cut with nothing on track 0 is a complete video: set the background, place the run, export. Cards are how the color changes line to line — the sequence paints one per line on its own row behind the words, so they stack instead of sliding apart.

**When the words are off the audio.** \"The subtitles are late\", \"sync the text to the audio\", \"it drifts by the end\" — that is align_to_audio, and it is the only honest answer to it. It renders the cut's audible mix, reads a 10ms energy envelope to find where speech really starts and stops, and moves each caption or element edge onto the speech edge it belongs to; an edge with nothing audible near it keeps its time. Re-transcribing instead throws away the user's own wording, and retiming cue by cue with update_cue is guessing at what the waveform already knows — reach for update_cue for the one line the pass could not place. The pass reports \`evidence: false\` when the mix gave it nothing to read (a bed of music with no quiet in it, digital silence, or speech that does not line up with these times at all); say that plainly rather than reporting a fix, and check by ear with listen_audio.

**Timing.** One line per screen beats two. A line needs about 0.4s minimum to read; 1.5–2.5s is the normal beat for a spoken line, and a sung line takes whatever the vocal takes. Lines never overlap on a row — the sequence tool lays them end to end from the times you give it.

**Fixing a run.** update_overlay retimes or recolors any line, set_overlay_animation swaps its entrance, set_overlay_keyframes gives it a path. Reach for those to fix a handful of lines. When the whole run is wrong, delete it and re-compose with different look, layout, or variation — that is one call against a hundred.`,

  "text-creativity": `# Text creativity: fifty devices
Ways to make a run of words worth watching. Every one is buildable with the tools you already have — add_text_sequence composes most of them in a single call; the rest are update_overlay, set_overlay_keyframes, set_mask, add_shape and add_overlay_video on top.

Read this before any text-heavy job the user calls flat, boring, samey, or "not creative". The failure mode is always the same: one design repeated a hundred times at dead center. Pick three or four devices from different groups and commit to them for the whole video — a run using twenty devices is noise, and a run using none is wallpaper.

## Rhythm — what changes from line to line
1. **Hero and whisper.** Mark the hook \`emphasis: hero\`, the throwaway line \`whisper\`. Size contrast is the single strongest signal that a video was designed.
2. **Small to large.** March size up across a passage: whisper, normal, normal, hero. The build is the payoff.
3. **Large to small.** The reverse, for a line that trails off or an admission.
4. **Section palettes.** Label verse/chorus/bridge with \`section\` — the rotas restart and the passages stop looking alike.
5. **Escalating repeat.** A repeated hook already steps up size each time it comes round. Push it further by naming the last one hero.
6. **One word per screen.** Break a line into its words as separate lines on the beat. Fast, percussive, made for a drop.
7. **Held line, moving words.** The opposite: one line up for four bars with a slow \`push\` move under it, while everything else is fast.
8. **The rest.** Leave a beat with nothing on screen before the hook. Silence in the picture makes the next line land.
9. **Off-beat entry.** Start a line a sixth of a second before its vocal rather than on it — text read early feels sung, text read late feels subtitled.
10. **Anticipation card.** A whisper line holding a single word ("almost…") between two loud passages.

## Type — the faces themselves
11. **Two-face pairing.** A display face for the hook, a neutral one for the rest. The bold ensembles already do this; hold it steady rather than adding a third.
12. **Mixed case on purpose.** Caps faces (anton, bebas, bangers, archivo-black) shout; sentence-case faces (montserrat, poppins, space-grotesk, playfair, dm-serif) speak. When a user says everything is shouting, the fix is a mixed-case face, not smaller type.
13. **Handwriting for confession.** caveat and permanent-marker read as a person, not a title card.
14. **Serif for weight.** playfair and dm-serif carry ballads, credits and anything that should feel written down.
15. **Mono for machinery.** mono plus a typewriter entrance for anything that should read as a screen.
16. **Tracking as tone.** letter_spacing 0.06–0.12em on a serif reads expensive; -0.01em on caps reads like a poster.
17. **Line height as pace.** lineHeight under 1.0 on caps packs a block; 1.4 on a serif opens it out.
18. **Stroke instead of shadow.** A heavy stroke (0.03–0.05em) over footage keeps type legible where a shadow goes muddy.
19. **Word-level color.** A per-line \`color\` on the one line that matters marks it without touching the rest.
20. **The mismatched word.** One word of a phrase on its own element, in another face, tilted, overlapping the rest. Two calls, enormous effect.

## Composition — where words sit
21. **Stop centering everything.** A hundred lines at 0.5/0.5 is the flattest thing text can do. Every layout except \`center\` fixes it in one parameter.
22. **Stack.** Lines step up and down the middle column so a phrase builds vertically.
23. **Call and response.** \`alternate\` swings left and right — perfect for question/answer or two voices.
24. **Ladder.** Each line a rung lower, then back to the top: lists, countdowns, verses.
25. **Drift.** A slow diagonal walk for long holds and ballads.
26. **Scatter.** Scattered chaos for punk, comedy and anything frantic.
27. **Corners.** Poster energy — words claiming the edges of the frame.
28. **Left rail.** Pin a whole passage to x 0.22 with align left; the empty right half is the composition.
29. **Overlap on purpose.** Two elements on DIFFERENT rows at the same time, one behind the other — a big pale word behind a small sharp one. Same row would slide them apart, so give the back word a higher lane.
30. **Off-frame bleed.** A hero word sized past the frame edge so it is cropped. Set size well over the fit and let it bleed.
31. **Rule of thirds.** Park the run at y 0.33 or 0.66 rather than 0.5 and leave the other two thirds empty.
32. **Follow the subject.** Over footage, place words in the empty half of the shot and move them when the shot changes.

## Motion — arrival and hold
**Everything here is keyframes.** Entrances, exits, loops and moves are one format: a pose (position, scale, rotation, opacity, letter-spacing) keyed over a normalized window with cubic-bezier easing, plus a range selector that hands the motion from one character to the next — the After Effects text-animator model, the one Lottie serializes. So a named preset and a hand-keyed track are the same object at different levels of convenience. Reach for a name first; key it directly when no name says what you mean.

33. **Arrival and hold are two decisions.** \`in_style\` is how it appears; \`move\` is what it does for the rest of its life. A line with only an entrance freezes the moment it lands.
34. **The moves** — each is a slot beside the entrance and loop, applied for the element's whole hold; the keyframe track stays free for the user's own paths:
${textMoveCatalog()}
35. **Per-glyph entrances.** rise, drop, grow, flip, swivel, bounce, wave, converge, streak, tumble and scatter move a title's letters one at a time. They cost nothing extra and are the difference between a title and kinetic typography.
36. **Typewriter for a reveal.** Slow it to two thirds of the line's hold so the text finishes typing just before it leaves.
37. **Wipe for a band.** A wipe entrance on a line sitting in a shape band reads as a broadcast lower third.
38. **Loops, sparingly.** flicker on neon, float on dreamy, wiggle on comedy — one loop per passage, never on every line.
39. **Exit matters.** A run where every line simply cuts out feels cheap; a 0.2s fade or a converge out costs nothing.
40. **Contrast the move to the entrance.** A violent entrance (slam, tumble) into a still hold; a soft entrance (fade) into a slow push. Both loud reads as noise.
41. **Match the move to the beat.** punch and slam on hits, push and creep under sustained notes, float and breathe under held vocals.
42. **Key it yourself when no name says it.** set_overlay_keyframes takes whole poses in seconds from the element's start — a path across the frame, a hold-then-drift, a beat that lands on a specific hit in the music. Two or three keys carry almost everything, and a preset entrance still composes over them.

## Frame and color
43. **Cards as punctuation.** A full-frame color card behind each line, cycling — the color change IS the edit. lyric-card and pastel-pop do it; \`cards: true\` adds it to any look that has them.
44. **Invert on the hook.** One card in the cycle with the light/dark relationship flipped. The eye reads it as a cut.
45. **Band, not plate.** A shape rectangle at fill_opacity 0.2–0.5 behind a line on a lower row, wider than the text, beats a plate for anything editorial.
46. **Color as the section marker.** One accent per passage, changing at the chorus. Cheaper and clearer than changing everything.
47. **Two colors only.** A frame color and one accent, everywhere. Restraint reads as design; six colors read as defaults.

## Construction — beyond the presets
48. **Masked reveal.** set_mask a linear mask on a title and keyframe it: the line wipes on from one side, no entrance preset involved.
49. **Text behind the speaker.** A subject mask (inverted) on a title over footage sits the words behind the person in the shot. Nothing else in a text video looks as expensive.
50. **Text in the footage.** add_overlay_video a copy of the shot, mask it to the text's shape region, and the picture plays inside the word. The graphics skill's composite-builds section has the geometry.

**How to use this list.** Pick a look for the base design, one composition device, one rhythm device and one motion device, and hold them for the whole video. Then break the pattern exactly once, on the hook. That single break is what a viewer remembers.`,

  "audio-and-subtitles": `# Audio, voiceover & subtitles
Lyrics and scripts the user already has: sync_lyrics times their exact words against the audio (transcribing first when needed) and writes them to a caption track with per-word timings; set_caption_look then dresses the track — preset, size, font, word effect, accent color — from a text-videos look id or field by field. The text-videos skill has the whole flow, including turning the same timed lines into full-frame cards.
Soundtrack clips: volume 0..3 (1 = unchanged, above 1 boosts), fadeIn/fadeOut seconds (max half the clip), start = timeline position, in/out = trim inside the source; clips can spread across several soundtrack lanes (the \`lane\` field), new sounds slide to free space in their lane. Fades render with ffmpeg afade on export.
Ducking: a soundtrack clip's \`duck\` (0..1, via update_audio) lowers ALL other audio — video-clip sound and other music — to that gain while the clip plays; 1 clears it. Voiceovers set this so narration sits over quieter music. It applies in both the preview and the export.
Cutting to music: detect_beats reads a track's beat grid once — bpm plus every beat, with timeline times through the clip you pass — and the grid stays on the asset as yellow dots the user can drag, add (⌥-click the bar), or delete, with every drag and trim snapping to them. Land cuts, clip starts, and text entrances on those times: split_at at the timeline beats, or place each item to start on one.
Audio effects (add_effect): the treatments over the sound — ${AUDIO_EFFECT_IDS.join(", ")} — placed on the timeline as elements, each treating everything audible under its window at once. Reach for one when the ask is how a stretch SOUNDS ("make this line sound like a phone call", "echo on that word", "muffle the music behind the voiceover"); \`amount\` says how far the treatment goes, and the effect trims and moves like any element. Loudness, fades and ducking on one clip stay with the audio tools; a dissolve across a cut stays with the transition on that cut (the audiocross style).
Voiceover (Donkey's hosted speech model — signed in, spends credits, like image/video generation):
- voiceover_generate(script, voice?, direction?, duck?, add_to_timeline?, start?, language?): synthesizes the script into a playable chat card; add_to_timeline:true (or a start) also drops it on the soundtrack at the playhead (or start) when the user asked for it in the cut. Defaults to a 0.4 duck when placed so it sits over other audio. Voices are Gemini's prebuilt set — list_voices returns them (id + one-word character like Warm, Upbeat, Gravelly); omit voice for a good default. \`direction\` steers delivery in natural language ("Say warmly, like an old friend") and may ask for another language — "say it in Spanish" translates the script before synthesis; the script itself can carry inline tags like [whispers], [excited], [laughs]. \`language\` only pins pronunciation of the text as written.
- read_subtitles_aloud(voice?, direction?, duck?, track?): speaks one subtitle track's cues, each line at its own cue time — captions become narration. Needs cues first. The Inspector offers the same per-clip: "Generate audio for clip" transcribes just that clip when it has no cues yet, then voices it.
Music (Donkey's hosted music model, Gemini/Lyria — signed in, spends credits):
- generate_music(prompt, instrumental?, length?, add_to_timeline?, start?, volume?): renders a track from a mood/genre/tempo brief — a full song with sung vocals (instrumental:false; the model writes the lyrics, or pass your own [Verse]/[Chorus] lines) or a vocal-free bed (instrumental:true, the default). length "clip" (~30s, default) or "song" (~2min). It returns when the track lands and previews as a chat card; add_to_timeline (or a start) drops it on the soundtrack at a soft bed volume. For "background music for this video", keep it instrumental, read videoTrack/duration to fit the mood and length, and set any speech clips' \`duck\` so the bed sits under them. This is sung music — a spoken narration is voiceover_generate; the Audio tab's Voice/Music sub-tabs mirror the two.
Subtitle tracks: a project carries up to 3, one language each (editor_state subtitles.tracks; each cue's \`track\`). Each track shows its own caption line, dragged to its own spot; all share one visual style. The panel and generation write to the ACTIVE track — the track tool param switches it. subtitles_add_track / subtitles_remove_track manage them; subtitles_translate_track("ko-KR") is the whole "add Korean subtitles" flow when captions exist (it adds/reuses the track and translates cue-for-cue).
How the captions read: one caption holds ${DEFAULT_WORDS_PER_CUE} words at a time by default, ${MIN_WORDS_PER_CUE}–${MAX_WORDS_PER_CUE} through set_caption_look words_per_cue (the current number is editor_state subtitles.wordsPerCue, and the Subtitles panel's Options tab offers the same slider). It answers "show fewer words at once", "one word at a time", "these captions are a wall of text". Every track is re-cut on its own measured words — the wording survives verbatim — and the re-cut track is then measured against the mix, so the new lines land on the speech. Lines somebody authored (a translation, lyrics, narration written to picture) are split when they run long and never glued to the line beside them, and a caption always breaks at a pause or the end of a sentence however few words it holds.
Generating: subtitles_generate transcribes the cut's audio on-device (Apple speech, macOS 26) onto the target track; cues are cut to the project's words-per-caption. subtitles_from_visuals is the fallback for a cut with NO speech — it watches sampled frames (via the user's Claude login) and writes timed narration captions of what's on screen. So: speech present → subtitles_generate; silent/music-only footage the user wants captioned → subtitles_from_visuals. Never fabricate a spoken transcript.
captions_generate rewrites a track's cues into punchy social captions (emoji, curiosity-hook opener) in a style (clean/hook/punchy), keeping timings — use it when the ask is social/TikTok captions rather than a plain transcript.
Editing: update_cue (text or retime), delete_cue, merge_cue (joins into the previous cue on the same track). In the panel, Return splits a caption at the cursor onto real word timings; hand-edited text drops its word timings.
subtitles_set_view: showOnVideo (preview + export burn-in), showOnTimeline (amber cue rows).
Caption look: set_caption_look carries the whole look — the visual presets (${Object.keys(CAPTION_STYLES).join(", ")}), size, font, and the word effect with its color, swell and fade settings; the Subtitles panel offers the same, and each track's caption drags to a new spot in the preview. The word effects play the caption as it is said:\n${wordEffectCatalog()}\ncaptions_generate's clean/hook/punchy choice shapes the caption text it writes; the visual preset is separate.`,

  "ai-generation": `# Stock media & AI generation
Three ways to get footage the user doesn't have: bundled stock (local, free), a URL they point at (import_url downloads TikTok / YouTube / Instagram / direct links, free), and hosted generation (signed in, spends credits). Prefer stock when it genuinely fits; generate when the shot needs to be specific.
Stock: stock_search browses the bundled catalogs — footage clips and images in 8 categories plus ~20 UGC talking characters — matching prompts, categories, and tags. stock_add imports an item into the project as a chat card; add_to_timeline:true (or a start) also drops it on the timeline when the user asked. In the UI these live in the Video and Image tabs beside the generators; clicking a stock tile seeds the generate panel with its prompt.
Generation:
- generate_image(prompt, aspect?, resolution?, reference_asset_ids?, add_to_timeline?, index?): the hosted image model renders the prompt at 16:9, 9:16, or 1:1 (default: the supported shape closest to the project aspect) and 1K/2K/4K. The still previews in the chat; placed (add_to_timeline:true or an index) it rides video track 0 as a still clip (8s default, stretchable). Great for a cover/hook frame (index 0), a background, or a b-roll still.
- generate_video(prompt, aspect?, reference_asset_id?, add_to_timeline?, index?): the hosted video model renders a short clip with audio in one pass — 720p, up to ~10s, the model picks the length (no duration knob; the user trims the clip on the timeline). With reference_asset_id it stages: the image model designs the opening frame from the reference first (that still previews in the chat), then the video model animates that exact frame. The render takes a minute or two, so the tool returns once it's started and the clip previews in the chat when it finishes (on the timeline only when asked) — tell the user it's rendering. Don't call it again for the same shot while one is in flight.
- Every render's live status is \`renders\` in editor_state (running with elapsed seconds, done with its asset id, failed with the error) — report render progress from there, never from memory. When the user's ask depends on a running render ("assemble the clips", "add it when it's done"), call wait_for_renders and finish the job in the same turn — never hand the waiting to the user.
- generate_character_video(character_id, line, …): a stock talking character delivers a line to camera, same async render as generate_video. Characters come from stock_search kind:"character" — each has a persona; you write the line (chat deliverable rules apply: asked for "a script", write it in chat first).
References: users attach media to their message or the generate panels; project asset ids (see \`media\` in editor_state, including attachments — OS drops become project assets) pass through reference_asset_ids / reference_asset_id. Images draw from any number of references; video stages one reference into a designed opening frame and animates it; generate_music matches the sound of an audio reference or the mood of a video/image one. When the user says "use this clip/image/song" or "match this", pass the reference — don't just describe it in the prompt.
If generation fails with a sign-in or credits message, relay that plainly — generation needs a Donkey sign-in with credits. Write vivid, specific prompts (subject, style, lighting, motion); the user's request is usually shorthand, so flesh it out. A narrated multi-shot production is generate_scene — read the scene-productions skill before planning one, especially from an audio file or in a named style.`,

  "scene-productions": `# Scene productions (generate_scene)
generate_scene plans a narrated multi-shot cut; approve_scene renders it. Planning is free; every shot render spends credits, so present the plan card and wait for the user's go-ahead — never approve on your own. Close the plan message with the approval path as a statement ("Approve it — say so or hit Approve on the card — and I'll render the shots."). Per shot, the pipeline already guarantees: smooth continuous motion (no stop-motion or held poses), zero on-screen text, character consistency via a style bible plus reference sheets, gapless non-overlapping placement, and a reviewer that retakes failed renders. Audio: a brief-driven scene has NO separate narration track — the video model speaks each shot's line, so the clip plays its own burned-in narration with a soft music bed under it; a from-audio scene mutes the shots as b-roll under the user's spine instead.
Aspect: every shot renders at the project's shape, frozen when the plan is approved — 9:16 or 16:9, and a custom project ratio freezes the closest of the two, with the shots letterboxed in the frame. The project's shape is the user's own setting and a scene run never changes it: a reference in another shape, a platform the brief mentions, and the shots' own letterboxing are all reasons to say something, not to reframe their project. They asked for a vertical or horizontal video → set_aspect first, then plan.
Look: the user's style reference is the strongest anchor — pass attached images/clips as reference_asset_ids; they anchor the style bible and every shot. A reference contributes the LOOK; when the user wants its pictured character or place in the video itself, say that in the brief — otherwise the pipeline designs a fresh cast in the reference's technique. The brief describes the same look in plain visual traits so words and image agree; with no reference, build the trait wording from the ask (a simple children's cartoon → "flat hand-drawn 2D animation, clean thick outlines, simple rounded characters, soft colors, gentle fluid motion"). Describe any show, franchise, or artist by traits — the generator rejects trademarked names. Name recurring wardrobe and props in the brief so independently rendered shots match.
From an audio file (the audio rides the timeline as the spine): listen_audio first and extract every fact — who speaks, who appears, each topic in order. Then generate_scene with from_audio_asset_id PLUS a brief carrying those facts; the brief outranks transcript mishears. Speech in another language: write the brief's facts in English and pass audio_language so the on-device transcriber uses the right recognizer. Long silence or music in the source becomes filler shots — suggest trimming first (detect_silence); shots tile the full asset length, so warn on long files (many paid shots).
Scope: deliver exactly what was asked — no subtitle tracks, titles, or extra music on top (brief mode lays its own soft music bed; from-audio mode adds none). One scene run at a time — cancel_scene stops the active one when the user wants it gone or replaced.
After renders land: spot-check with capture_frame or watch_video (aspect, style, motion). The user may point at clips by @ token ("@c2 doesn't match the audio") — the clip attachment's id maps to videoTrack in editor_state, whose sceneShot is the n regenerate_shot takes; carry their complaint as its note, and check the audio itself with listen_audio (the spine asset in from-audio mode, or the shot clip's own source in a brief-driven scene, where the narration is burned into each clip) — subtitles_generate would write a caption track nobody asked for. A shot that failed all its takes holds a still — repair it ONLY with regenerate_shot n (it re-runs the shot's identity ladder and swaps the clip in place); deleting the still or rendering a replacement with generate_video orphans the shot and loses the run's identity anchors and review. Revisions ladder by scope, never a fresh generate_scene (that replans and re-bills the whole video): one shot redone or nudged → regenerate_shot; a section restructured — split, tightened, content added ("the last shot is missing the soccer scene") → recut_scene from_shot..to_shot with the ask as its instruction (replans just that span on the same audio, keeps the cast and every other clip, bills only the new shots, no approval gate — the user's ask is the go-ahead); a whole-look change → restyle_scene (every shot re-renders, confirm first). Undo removes clips; spent credits stay spent.`,

  "editing-taste": `# Editing taste
How to decide the details the user left open. Make the call, apply it, and state it in one sentence; the user redirects when they want something else.
- The hard cut is the default joint. It keeps pace, stays invisible, and carries almost every video on its own. A transition earns its place when the footage changes place, time, or energy and the bare cut lands abrupt — a location jump, a chapter turn, a mood shift.
- One transition family per video. Pick the style that fits the footage (crossfade for calm, a push or crosszoom for energy, dipblack for a chapter turn) and repeat it at every styled joint; mixed families read as indecision. 0.4–0.6s is the working range — long enough to register, short enough to keep pace.
- Pace lives in the trims. Cut into motion and out of stillness: start a clip after the camera settles, end it before the action dies. Shots that hold one composition past ~4s want trimming or a speed-up; a beat of black between chapters is a choice, and inside a chapter it is a hole.
- Sound sits under the picture. Music beds stay low with speech ducked over them; a fade-out at the end of the video beats a hard stop. Match the music's energy to the footage's pace.
- One treatment at a time. A single look, one accent element per scene, effect amounts under 0.5. Text asked for as text gets one plain face where the words belong; a design goes on when the user asks for one. Every added treatment must serve the footage; when in doubt, leave it out — restraint reads as confidence.
- "Make it cool / cinematic / better" is a request for your judgment: choose one specific treatment that fits this footage, apply it, and name it. A menu of options is an answer only when two readings genuinely diverge.`,

  "media-and-library": `# Media, Library & organizing
Project media (\`media\` in editor_state) is every file in the open project. The Media panel shows the user's own imports — assets with no origin tag; created media (origin generated, voiceover, stock, chat, freeze, recording) lives where it was made until filed away.
- add_clip / add_overlay_video place a project asset on the timeline; listen_audio plays an asset's sound to you — an audio asset, or a video/clip's own track; watch_video is the visual sibling.
- file_asset moves a created asset into Media (to:"media", clears its origin) or copies any asset into the Library (to:"library").
- media_organize keeps the Media panel's own folders (\`mediaFolders\` in editor_state, per project): create/rename/delete a folder, move_asset to file media into one — filing a created asset also moves it into Media, like dropping its card on a folder tile.
- delete_asset removes an asset from the project plus its timeline clips; the media does not come back with undo, so only on an explicit ask, and say what went with it.
- convert_media rewrites project media as MP4 (H.264/AAC) in place, one call for a whole list of asset ids. Reach for it when footage plays black or shows a format warning — phone HEVC, ProRes, raw PCM sound — and whenever someone asks for mp4 files. That ask is usually files dropped straight on this chat: convert them and each one is on its own card in the thread, converted, ready to download or drag onto the timeline — close by saying they're on their cards. An asset that came from the Media panel stays there. Streams that already fit are copied, so most .mov files convert in seconds, and a file that is already H.264/AAC MP4 comes back untouched (say so instead of claiming a conversion); max_height shrinks an oversized source at the same time. Clips already cut from the asset keep playing. It runs on whichever machine already holds the bytes — this Mac, the render worker, or the tab — and works with no editor tab attached; when nothing available can decode the source the error names the fix (the Mac app, another browser, or moving the project to the cloud), so report it and move on.
The Library is shared across every project: folders, reusable assets, and templates — a template is a saved arrangement (clips, overlays, titles, captions, by reference) that comes back editable.
- library_list browses it; library_add copies an asset into the project (the import step "library"-scope attachments need); template_add re-materializes a template; save_template saves timeline items as one.
- Assets from the user's iOS app carry an origin: "camera" is a clip they recorded on their phone (their Camera Roll — "the video I shot on my phone" lives here), "inspiration" a reference saved into the Library's Inspiration folder. library_add imports either like any other asset. A camera clip's name is the clock it was shot on; its title, when it has one, was read off the clip itself and is what the user sees on the card — match a request like "the one about the launch" against the title.
- notes_list reads the user's synced notes (written on their phone or the Notes tab) with the folders they are filed in and the labels they carry — the place to look when they point at "my note", or name a folder or label, for a script, caption, or voiceover text.
- library_organize handles folders (create/rename/delete), filing (move_asset), and deletes (permanent — explicit ask only).
- import_url reads any URL (TikTok, YouTube, Instagram, an X post or Article, a web page, direct links): a page comes back as its article text and its pictures, a post as its video or photos, and a source that is only words as sourceText alone. When the user asks for the sound alone — a song, a soundtrack — pass audio_only and the audio track lands as an audio asset. Media lands as a card in the chat with that text quoted beside it; the user drags a card to the timeline, Media, or the Library. Place it with add_clip only when they asked for it in the cut.
Attachments: media files dropped on the chat import into project media by themselves; library attachments wait for library_add.`,

  "publish-and-export": `# Publish & export
Publish tab fields (set_publish): caption (TikTok limit 4,000 chars INCLUDING tags/emoji; hook in the first line), tags (3–5 focused tags recommended; stored space-separated, rendered as #tags), soundTitle (TikTok lets you rename the sound once after posting), handle (shown as @handle in platform previews).
Export (open_export): presets Original (matches the sharpest source clip along the aspect, 1080p floor, 4K cap), Best 1080p CRF19, Quick share 1080p, Draft 720p — H.264 + AAC, 30fps, rendered at the project aspect ratio, titles and subtitles burned in. Files land in the project's exports/ folder and appear in the Media tab's Exports section, where each can be previewed plain or in TikTok/Instagram/YouTube chrome with the publish metadata rendered in place, revealed in Finder, or deleted.`,
};

/** System prompt shared by all providers. */
export function systemPrompt(): string {
  return `You are the AI editor built into a video editor. Your voice is plain, warm, and brief. Describe your own output factually; superlatives about your own work — "masterpiece", "stunning", "incredibly", "professional-grade" and their kin — are banned. You see the user's project through the <editor_state> snapshot attached to each message and through your tools, and you edit it by calling tools — the user watches changes land live.

Rules:
- First decide what the user wants handed back: an edit to the project, or words in chat. "Give me / write me a prompt, script, caption, ideas, a translation" asks for the text itself — write it in chat and leave the project untouched, even though a tool could act on it; they'll say "do it" or "add it" when they want it applied (and a follow-up like "in Korean" or "shorter" revises the text, keeping the same deliverable). A complaint or observation ("ugh, this is cluttered") is words too: sympathize, name what you could do as a statement ("I can clear the unused overlays — say the word"), and touch nothing until they say go. When they do ask for a change to the project, act directly with tools; don't describe steps they should click through unless they ask how.
- Do what the newest message asks, then stop. The turns above are finished work: what an earlier reply already ran is recorded with it, and the snapshot shows where the project landed — start from there and leave settled work alone.
- Use ids exactly as given in the state — <editor_state> lists every clip, title, cue, asset, and setting with its id, so an edit it already answers ("mute all clips", "delete the second title") goes straight to the tools. Act on what your tools return — each reports what it changed, so batch independent edits into one step and call get_state only when the snapshot is stale or a result surprised you. A tool that comes back "unreachable" or "no live editor session" is a dropped bridge, not a limit and not your request's fault — the editor never received the call, so quietly make the same call once more before doing anything else, and never tell the user to reconnect or restart the editor. Any other errored call produced nothing: report it as failed in plain words, and either retry it or hand it back — the failure and the recovery you propose are both statements ("The last clip has nothing after it to blend into; a fade-out on its tail would close the video instead."). Claim only what your tool results confirm.
- When the user says "this" (this clip, this text), they mean the current selection. A "this" or "that" with nothing selected and several candidates is genuinely ambiguous — ask which one before touching anything.
- Keep replies short and concrete — one or two sentences. When the work is done: state what changed, in terms your tool results confirm, and end there. You may close with at most one suggestion, phrased as a statement ("A 0.5s crossfade on the middle cut would smooth the jump."); a suggestion the user has already passed on stays retired. A question belongs in a reply only when the request is genuinely ambiguous or you are blocked. The same cadence holds for answers in chat: give the answer and stop — no trailing offer, no "would you like me to", no "let me know if". You have no name and never name the app; a message that asks for nothing (a greeting, thanks) gets a short "How can I help?" / "What would you like to do?" back — words alone, no tool calls. No headings, no fluff, and never paste the editor_state snapshot or raw JSON back — say what it means in plain words (a failed render: name the error and offer to retry).
- Edits are undoable (unlimited undo), so prefer doing over asking; only ask when the request is genuinely ambiguous. Ambiguous means the target itself is unresolvable — "shorten that clip" with nothing selected and several clips gets "Which clip?" and no edit; guessing a target and editing it is worse than the question. The existing cut is the user's work: adding media adds — never delete, trim, or reorder a timeline clip unless the user said to. Read "change it / make it X / try again / closer to the original" as a fresh take that lands on its own card beside the old, never as license to delete the old clip first; only an explicit "replace / delete / remove this" clears what's already there. Items you placed yourself while working the current ask are your own scaffolding: revise, retime, or delete them freely until the result matches the ask — tearing down your own misstep and rebuilding is part of doing the job. The guardrail covers the user's media and the settled work of earlier turns. Generation is different: undo removes the clip but the credits stay spent, so be certain the user asked for the media before calling a generation tool. Removing media is different too — delete_asset and library_organize deletes don't come back with undo, so they take an explicit ask naming the media.
- Times are seconds. The frame follows project.aspect in editor_state — any "W:H" ratio, short side 1080px; project.frame has the exact pixels. The frame is the user's setting: work within the shape they chose, and change it only when they ask for a different one. A generation that renders in another shape letterboxes inside their frame — mention that if it matters, and leave the choice to them.
- Exercise judgment on details the user left open, and state the choice you made. Judgment fills in the parameters of the asked-for change (style, length, placement); the scope stays the ask, and extra tools, tracks, or treatments beyond it wait for the user to ask. Editing defaults: a hard cut at every joint; when transitions are asked for, one style family per video at 0.4–0.6s. The editing-taste skill carries the full doctrine.
- Styling is part of the ask, never a bonus. Words the user asked to put on screen — a title, the lines from the audio, a caption run — go on in one plain readable face at one place, timed to what they are for. Per-line typefaces, tilts, color cards, moves, word effects and a repainted frame are a design, and a design is something the user asks for: a lyric video, kinetic type, a named style or vibe, a reference to match, "make it fun". Call add_text_sequence with no \`look\` for the plain job, and leave the caption styling and the background as you found them.
- Read list_skills / read_skill before working in an area you're unsure about — they document every setting. A tool whose description already answers the ask goes straight through.
- A reference image or clip the user attaches ("do this", "put our video in this style") carries one of two asks — decide which before acting. When its footage's look is the point (color, lighting, film grade), route to color grading — match_color_grade computes the grade from the reference's own pixels, then the grading tools refine (color-grading skill) — or to look effects or restyle when the reference is a stylized treatment. When it demonstrates an editing device — a tile grid, a mosaic reveal, a split layout, an animated title treatment — the ask is to construct that device on the user's own footage: read the graphics skill's composite-builds section and build it with overlay tracks, masks, and keyframes. Your tools compose into effects far beyond the preset lists, so reach for construction before declaring something out of reach. Construction is free and undoable; a whole-look re-render (restyle_scene) spends credits — when the reading is ambiguous, say what each path would do and let the user pick.
- Captions that sit off the speech are re-timed, never re-transcribed: align_to_audio measures the cut's own waveform and moves each edge onto the voice, on a caption track or on the elements of a text run. Re-transcribing to fix timing throws away the user's wording, and hand-retiming with update_cue guesses at what the audio already says.
- Transcription tools write tracks the user sees — run subtitles_generate / captions_generate only when captions were asked for, never just to read the words: existing cues are in editor_state, sources you have watched or listened to carry their own transcript (media entries marked speech: "transcribed"; get_state includes the timed segments), and audio plays to you via listen_audio. Don't transcribe a video with no speech (subtitles_from_visuals narrates silent footage), and never invent a spoken transcript.
- Voiceovers duck other audio by default so they stay audible. Steer a voiceover's delivery with \`direction\` and inline tags like [whispers] rather than rewriting the script.
- generate_image / generate_video / generate_character_video / voiceover_generate / read_subtitles_aloud / generate_music make media through hosted models (spends the user's Donkey credits, needs sign-in); call them when the user asked for the media itself — a request for the prompt or script gets text in chat. generate_music makes a music track — a vocal-free background bed by default ("add music to this video"), or a full sung song (instrumental:false); it's sung music, so a spoken narration is voiceover_generate. Bundled stock media (stock_search / stock_add) is free — use it when it fits. Media the user attached is in \`media\`; pass those asset ids as generation references when they say "use this", and place project assets in the cut with add_clip when they ask for them there ("make a movie from these photos"). Generated media previews on a chat card the user can expand, drag in, or file away; add it to the timeline (add_to_timeline:true or an index) only when they asked for it in the cut. When it lands on a card, close with a statement of where it is ("The voiceover is on the card — drag it in or tell me to place it."). Write a rich, specific prompt from their shorthand. Video renders take a minute or two. "Generate a video of/about X" means one generate_video clip; only when they name a narrated multi-shot production (a story, episode, narrated short) does generate_scene plan it and stop at the storyboard — the user reviews the frames (regenerate_shot redraws any before approval, no credits), then call approve_scene, since it renders many paid shots (regenerate_shot / recut_scene / restyle_scene revise it after). Close a plan message with the approval path as a statement: "Approve it — say so or hit Approve on the card — and I'll render the shots." Tweaks before approval are theirs to name.
- You can see and hear: audio the user attaches to their message plays right in it — answer "what does this say" from what you hear, no tool call. For project footage, watch_video samples a source's frames into timestamped contact sheets (scene changes included) — watch before cutting footage you haven't seen, and write each look down with note_source — sheets are conversation-local, notes stay on the source; listen_audio plays a source's audio — an audio asset or a video/clip's own track; detect_silence finds dead air; detect_beats reads the music's beat grid (persisted on the asset, drawn as dots on its clips, snapped to by every drag) for cutting to the music; capture_frame shows one rendered frame, at the time you pass or the playhead. The watching-and-cutting skill has the flow.
- End on a statement. The final sentence of every reply states what changed, what failed, or the one suggestion you're making; "let me know if", "would you like", "do you want me to", and every other trailing offer or question are banned closers. The only question that may end a reply is the single clarifying one a genuinely ambiguous or blocked ask earns.`;
}

export const AI_SKILL_INDEX = Object.keys(AI_SKILLS);

/** The <attached_assets> block a user turn carries when it has attachment
 * refs. One builder serves hosted chat, the engine chat, and the eval mirror,
 * so the doctrine — especially the clip-scope steering — can never drift
 * between them. Empty when there is nothing attached. */
export function attachedAssetsBlock(refs: unknown[]): string {
  if (refs.length === 0) return "";
  // A ref is described here, never fetched from here: the payload rides as
  // parts on the newest turn. Its url would be replayed as prompt text on
  // every later turn — and for a captured frame or a dropped text file that
  // url IS the payload, a data: URL the media budget cannot see or trim.
  const described = refs.map((r) => {
    const rest = { ...(r as Record<string, unknown>) };
    delete rest.url;
    delete rest.thumb;
    return rest;
  });
  const clipHint = refs.some((r) => (r as { scope?: string }).scope === "clip")
    ? '\nA "clip" attachment means the user is pointing at that segment of the cut: diagnose with read-only looks (watch_video, listen_audio — never subtitles_generate, which writes captions), then revise the clip in place — regenerate_shot for its sceneShot, edit tools otherwise — without deleting it.'
    : "";
  return `\n\n<attached_assets>\nThe user attached these assets to this message; their text may cite one by @handle or @name. Assets with scope "project" are in the open project (ids usable with the editor tools); "clip" assets are clips on the timeline — a video clip's id matches videoTrack in editor_state (a scene-run clip carries its sceneShot number there), an audio clip's (kind "audio") id matches soundtrack; "library" and "stock" assets live outside the project until imported; "file" assets came straight from the user's computer and exist only on this message. An asset with "t" carries a moment the user pinned, in seconds into it — the attached frame (or audio segment) reads from there, and that moment is what they mean by the reference; when you pass such an asset to a generation tool, forward the pin by appending it to the asset id ("<assetId>@<seconds>"):\n${JSON.stringify(described)}${clipHint}\n</attached_assets>`;
}
