import type { IconKey } from "@mdxeditor/editor";
import {
  ArrowDownToLine,
  ArrowLeftToLine,
  ArrowRightToLine,
  ArrowUpToLine,
  Bold,
  Check,
  ChevronDown,
  Code,
  Columns3,
  Copy,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  FileCode,
  FileText,
  GitCompare,
  Highlighter,
  ImagePlus,
  Info,
  Italic,
  Link2,
  List,
  ListChecks,
  ListOrdered,
  Minus,
  PenLine,
  Pencil,
  Redo2,
  Rows3,
  Settings2,
  SquareCode,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignStart,
  Trash,
  Trash2,
  Underline,
  Undo2,
  Unlink,
  X,
  type LucideIcon,
} from "lucide-react";

// The editor's toolbar and popups draw the app's icon set.
const ICONS: Record<IconKey, LucideIcon> = {
  undo: Undo2,
  redo: Redo2,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  code: Code,
  strikeThrough: Strikethrough,
  superscript: Superscript,
  subscript: Subscript,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_list_checked: ListChecks,
  format_highlight: Highlighter,
  link: Link2,
  add_photo: ImagePlus,
  table: Table,
  horizontal_rule: Minus,
  frontmatter: FileText,
  frame_source: SquareCode,
  arrow_drop_down: ChevronDown,
  admonition: Info,
  rich_text: PenLine,
  difference: GitCompare,
  markdown: FileCode,
  open_in_new: ExternalLink,
  link_off: Unlink,
  edit: Pencil,
  content_copy: Copy,
  more_horiz: Ellipsis,
  more_vert: EllipsisVertical,
  close: X,
  settings: Settings2,
  delete_big: Trash2,
  delete_small: Trash,
  format_align_center: TextAlignCenter,
  format_align_left: TextAlignStart,
  format_align_right: TextAlignEnd,
  add_row: Rows3,
  add_column: Columns3,
  insert_col_left: ArrowLeftToLine,
  insert_row_above: ArrowUpToLine,
  insert_row_below: ArrowDownToLine,
  insert_col_right: ArrowRightToLine,
  check: Check,
};

export const EDITOR_ICON_CLASS = "size-4";

export function editorIcon(name: IconKey) {
  const Icon = ICONS[name];
  return <Icon className={EDITOR_ICON_CLASS} />;
}
