// Generated by scripts/build-builtin-luts.ts — do not edit by hand.
import type { BuiltinLut } from "./builtinLuts";

export const BUILTIN_LUT_MANIFEST: BuiltinLut[] = [
  {"id":"portrait","label":"Portrait","group":"color","file":"/cut/luts/portrait.cube","key":"ba54289d3d7db23f"},
  {"id":"natural","label":"Natural","group":"color","file":"/cut/luts/natural.cube","key":"6feccfb27127f0bc"},
  {"id":"pastel","label":"Pastel","group":"color","file":"/cut/luts/pastel.cube","key":"b082368580b5c19c"},
  {"id":"vivid","label":"Vivid","group":"color","file":"/cut/luts/vivid.cube","key":"a85d9064aa138b63"},
  {"id":"nature","label":"Nature","group":"color","file":"/cut/luts/nature.cube","key":"66a0be6eb29a8e64"},
  {"id":"heritage","label":"Heritage","group":"color","file":"/cut/luts/heritage.cube","key":"4bcb4b0bb7c40c69"},
  {"id":"crisp","label":"Crisp","group":"color","file":"/cut/luts/crisp.cube","key":"74983aa6b88b12d1"},
  {"id":"pop","label":"Pop","group":"color","file":"/cut/luts/pop.cube","key":"ff45068c2a2c6d8b"},
  {"id":"street","label":"Street","group":"color","file":"/cut/luts/street.cube","key":"4da4f3735c0524b5"},
  {"id":"summer","label":"Summer","group":"color","file":"/cut/luts/summer.cube","key":"f43e82b9a9dd4648"},
  {"id":"cross-process","label":"Cross Process","group":"color","file":"/cut/luts/cross-process.cube","key":"8c4bd95948c6b9e5"},
  {"id":"snapshot","label":"Snapshot","group":"color","file":"/cut/luts/snapshot.cube","key":"4d6cdc88394f991b"},
  {"id":"warm-fade","label":"Warm Fade","group":"color","file":"/cut/luts/warm-fade.cube","key":"b281372a553ea556"},
  {"id":"nostalgic","label":"Nostalgic","group":"color","file":"/cut/luts/nostalgic.cube","key":"74c6f15af556e592"},
  {"id":"dusty","label":"Dusty","group":"color","file":"/cut/luts/dusty.cube","key":"c670e8166de8aebb"},
  {"id":"press","label":"Press","group":"bw","file":"/cut/luts/press.cube","key":"1a10398b658876d8"},
  {"id":"documentary","label":"Documentary","group":"bw","file":"/cut/luts/documentary.cube","key":"e599f939f54e4415"},
  {"id":"infrared","label":"Infrared","group":"bw","file":"/cut/luts/infrared.cube","key":"63a0f222980d25e7"},
  {"id":"retro-mono","label":"Retro Mono","group":"bw","file":"/cut/luts/retro-mono.cube","key":"f1d678fc70d3c537"},
];
