// Generated by scripts/build-builtin-luts.ts — do not edit by hand.
import type { BuiltinLut } from "./builtinLuts";

export const BUILTIN_LUT_MANIFEST: BuiltinLut[] = [
  {"id":"portrait","label":"Portrait","group":"color","look":"warm, glowing skin, a touch brighter; flattering on people","file":"/cut/luts/portrait.cube","key":"ba54289d3d7db23f"},
  {"id":"natural","label":"Natural","group":"color","look":"gently warm, true-to-life color, clean whites","file":"/cut/luts/natural.cube","key":"6feccfb27127f0bc"},
  {"id":"airy","label":"Airy","group":"color","look":"bright and light, lifted midtones, warm with a little more color","file":"/cut/luts/airy.cube","key":"09e0bbbc298157ce"},
  {"id":"vivid","label":"Vivid","group":"color","look":"saturated, warm slide-film color with strong contrast","file":"/cut/luts/vivid.cube","key":"9c40ec8d61bfd5c2"},
  {"id":"heritage","label":"Heritage","group":"color","look":"rich reds, restrained greens, crisp whites; classic slide film","file":"/cut/luts/heritage.cube","key":"4bcb4b0bb7c40c69"},
  {"id":"crisp","label":"Crisp","group":"color","look":"neutral color, deeper midtones, clean whites","file":"/cut/luts/crisp.cube","key":"74983aa6b88b12d1"},
  {"id":"pop","label":"Pop","group":"color","look":"saturated and dense, deep reds, darker midtones","file":"/cut/luts/pop.cube","key":"ff45068c2a2c6d8b"},
  {"id":"street","label":"Street","group":"color","look":"warm, punchy everyday film color, bright whites","file":"/cut/luts/street.cube","key":"4da4f3735c0524b5"},
  {"id":"summer","label":"Summer","group":"color","look":"hot reds and magentas, saturated, darker midtones","file":"/cut/luts/summer.cube","key":"f43e82b9a9dd4648"},
  {"id":"cross-process","label":"Cross Process","group":"color","look":"strong cyan-blue cast, saturated; surreal","file":"/cut/luts/cross-process.cube","key":"8c4bd95948c6b9e5"},
  {"id":"snapshot","label":"Snapshot","group":"color","look":"faded instant film: lifted blacks, muted, cool-green shadows","file":"/cut/luts/snapshot.cube","key":"4d6cdc88394f991b"},
  {"id":"warm-fade","label":"Warm Fade","group":"color","look":"warm, lifted blacks, bright highlights; sunny faded film","file":"/cut/luts/warm-fade.cube","key":"b281372a553ea556"},
  {"id":"nostalgic","label":"Nostalgic","group":"color","look":"muted and softly faded, slightly cooler; old prints","file":"/cut/luts/nostalgic.cube","key":"74c6f15af556e592"},
  {"id":"dusty","label":"Dusty","group":"color","look":"dark, dense amber-brown, muted greens","file":"/cut/luts/dusty.cube","key":"c670e8166de8aebb"},
  {"id":"press","label":"Press","group":"bw","look":"black and white, even tones, bright whites","file":"/cut/luts/press.cube","key":"1a10398b658876d8"},
  {"id":"documentary","label":"Documentary","group":"bw","look":"black and white, dark and contrasty","file":"/cut/luts/documentary.cube","key":"e599f939f54e4415"},
  {"id":"infrared","label":"Infrared","group":"bw","look":"black and white, very bright, glowing highlights and foliage","file":"/cut/luts/infrared.cube","key":"63a0f222980d25e7"},
  {"id":"retro-mono","label":"Retro Mono","group":"bw","look":"black and white, hard contrast, deep blacks","file":"/cut/luts/retro-mono.cube","key":"f1d678fc70d3c537"},
];
